Update publish steps

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -16,18 +16,24 @@ jobs:
           fetch-depth: 0 # To get all tags
       - name: Set up environment
         uses: ./.github/actions/setup
-      - name: Check for changesets
+      - name: Create Version Packages PR or Publish
+        id: changesets
         uses: changesets/action@v1
+        with:
+          title: Version Packages
+          commit: Version Packages
+          version: npm run version
+          publish: npm run publish
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
       - name: Fail if changesets found
         if: steps.changesets.outputs.hasChangesets == 'true'
         run: |
           echo "Changesets found. Merge Version Packages PR before publishing."
           exit 1
-      - name: Publish
-        if: steps.changesets.outputs.hasChangesets == 'false'
-        run: npm run publish
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
+      - name: Fail if publish did not occur
+        if: steps.changesets.outputs.published == 'false'
+        run: |
+          echo "Publish failed. Check the logs for more details."
+          exit 1
